#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python36\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

star = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAABGdBTUEAALGPC/xhBQAAACBj'
    b'SFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QAAKqNIzIA'
    b'AAAJcEhZcwAADdcAAA3XAUIom3gAAAAHdElNRQfhCgwEHR2KyW2HAAABhklEQVQ4y43TMUtb'
    b'YRSH8d+1iogWBCuIUoSSRALtJ/ADCG5SOhQc3ZwFv0BXZxcXQRRKXTI5CQ6COKg0kdqQbkIk'
    b'AYe4SCOnQ5M0prdNzju9//M891wOvIm0GvEeX/w0YG0LYXtQPO/JnTtP8oMJe8KGDWFvEDyn'
    b'qWbcuJqmXH9hV9gEm8JuPzyjqW4CTKhryjwHhvHKO1lZOVlvvLDlATzY8knRD2XflZV9VWfd'
    b'o+icqv3W93/P2Fft6j5aT1RN2/dNWVlZI+U3X8rKysj7qMaxcGC47zKGHQjHzKsIh0b+i484'
    b'FCrmYc6NUDD6T3xUQbgx1w5mlIQjY6n4mCOhZKY7nHYp7KQKO8Kl6d54QThNFU6FhfZlqBO/'
    b'xnWqcN3q9ghvUUoVSq1ua7vdQrGzxA/43HpxxW7hT50JsxiyqiKEilVDmBXOevFEw73EiqIQ'
    b'CgpCKFqRuNeQPBcmhVvnQjixCBadCOHcrTDZO+FKCBeWn+XLLoRw1TuBKWuW/o4llqyZal9/'
    b'AcS7i3NaIjAhAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE3LTEwLTEyVDA0OjI5OjI5KzAyOjAw'
    b'Y7XGUQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxNy0xMC0xMlQwNDoyOToyOSswMjowMBLofu0A'
    b'AAAZdEVYdFNvZnR3YXJlAHd3dy5pbmtzY2FwZS5vcmeb7jwaAAAAAElFTkSuQmCC')

